/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useFrame, useLoader } from "@react-three/fiber";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function BuildingModel({ linkFile, ...props }) {
  // Sử dụng useLoader để tải model và clone scene cho mỗi instance
  const gltf = useGLTF(linkFile);
  const modelRef = useRef();

  const scene = gltf.scene.clone();

  return (
    <primitive
      ref={modelRef}
      castShadow
      theatreKey="building"
      editableType="group"
      object={scene}
      {...props}
    />
  );
}
