/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useFrame, useLoader } from "@react-three/fiber";
import React, { useRef, memo, useMemo } from "react";
import { useGLTF } from "@react-three/drei";

const BuildingModel = memo(({ linkFile, ...props }) => {
  // Sử dụng useLoader để tải model và clone scene cho mỗi instance
  const gltf = useGLTF(linkFile);
  const modelRef = useRef();

  // Sử dụng useMemo để cache scene clone
  const scene = useMemo(() => gltf.scene.clone(), [gltf.scene]);

  return (
    <primitive
      ref={modelRef}
      castShadow
      theatreKey="building"
      editableType="group"
      object={scene}
      {...props}
    />
  );
});

BuildingModel.displayName = "BuildingModel";

export { BuildingModel };
