/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useLoader } from "@react-three/fiber";
import React, { useRef } from "react";
import { editable as e } from "@theatre/r3f";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export function Building(props) {
  // Sử dụng useLoader để tải model và clone scene cho mỗi instance
  const gltf = useLoader(GLTFLoader, "/school_building.glb");

  // Clone scene để có thể sử dụng nhiều lần
  const scene = gltf.scene.clone();

  return (
    <primitive
      theatreKey="building"
      editableType="group"
      object={scene}
      // {...props}
    />
  );
}
